import Head from "next/head";
import Header from "@/componentes/Topo/Topo";
import Capa from "@/componentes/SecaoCapa/Capa";
import Produtos from "@/componentes/SecaoProdutos/Produtos";
import Sobre from "@/componentes/SecaoSobre/Sobre";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ótica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header/>
      <Capa/>
      <Produtos/>
      <Sobre/>
    </>
  );
}
